 Here's the API specification for the Test Run Tree structure:                                                                                                                                                
                                                                                                                                                                                                               
  ---                                                                                                                                                                                                          
  Test Run Tree API Specification                                                                                                                                                                              
                                                                                                                                                                                                               
  Data Model                                                                                                                                                                                                   
                                                                                                                                                                                                               
  {                                                                                                                                                                                                            
    "id": "uuid",                                                                                                                                                                                              
    "user_id": "uuid",                                                                                                                                                                                         
    "name": "string",                                                                                                                                                                                          
    "type": "folder | testrun",                                                                                                                                                                                
    "parent_id": "uuid | null",                                                                                                                                                                                
    "expanded": "boolean",                                                                                                                                                                                     
    "position": "integer",                                                                                                                                                                                     
    "test_cases": ["uuid"],  // Only for testrun type - list of test case IDs                                                                                                                                  
    "created_at": "datetime",                                                                                                                                                                                  
    "updated_at": "datetime"                                                                                                                                                                                   
  }                                                                                                                                                                                                            
                                                                                                                                                                                                               
  ---                                                                                                                                                                                                          
  Endpoints                                                                                                                                                                                                    
                                                                                                                                                                                                               
  1. GET /test-run-tree                                                                                                                                                                                        
                                                                                                                                                                                                               
  Get the full tree structure for the authenticated user.                                                                                                                                                      
                                                                                                                                                                                                               
  Response:                                                                                                                                                                                                    
  {                                                                                                                                                                                                            
    "structure": {                                                                                                                                                                                             
      "id": "root",                                                                                                                                                                                            
      "name": "ROOT",                                                                                                                                                                                          
      "type": "folder",                                                                                                                                                                                        
      "expanded": true,                                                                                                                                                                                        
      "children": [                                                                                                                                                                                            
        {                                                                                                                                                                                                      
          "id": "uuid-1",                                                                                                                                                                                      
          "name": "Regression Suite",                                                                                                                                                                          
          "type": "folder",                                                                                                                                                                                    
          "expanded": true,                                                                                                                                                                                    
          "children": [                                                                                                                                                                                        
            {                                                                                                                                                                                                  
              "id": "uuid-2",                                                                                                                                                                                  
              "name": "Test Run 2024-01-17 #1",                                                                                                                                                                
              "type": "testrun",                                                                                                                                                                               
              "test_cases": ["tc-uuid-1", "tc-uuid-2"]                                                                                                                                                         
            }                                                                                                                                                                                                  
          ]                                                                                                                                                                                                    
        }                                                                                                                                                                                                      
      ]                                                                                                                                                                                                        
    }                                                                                                                                                                                                          
  }                                                                                                                                                                                                            
                                                                                                                                                                                                               
  ---                                                                                                                                                                                                          
  2. POST /test-run-tree/folders                                                                                                                                                                               
                                                                                                                                                                                                               
  Create a new folder.                                                                                                                                                                                         
                                                                                                                                                                                                               
  Request:                                                                                                                                                                                                     
  {                                                                                                                                                                                                            
    "name": "New Folder",                                                                                                                                                                                      
    "parent_id": "uuid | null"  // null for root level                                                                                                                                                         
  }                                                                                                                                                                                                            
                                                                                                                                                                                                               
  Response:                                                                                                                                                                                                    
  {                                                                                                                                                                                                            
    "id": "uuid",                                                                                                                                                                                              
    "name": "New Folder",                                                                                                                                                                                      
    "type": "folder",                                                                                                                                                                                          
    "parent_id": "uuid",                                                                                                                                                                                       
    "expanded": false,                                                                                                                                                                                         
    "created_at": "datetime"                                                                                                                                                                                   
  }                                                                                                                                                                                                            
                                                                                                                                                                                                               
  ---                                                                                                                                                                                                          
  3. POST /test-run-tree/testruns                                                                                                                                                                              
                                                                                                                                                                                                               
  Create a new test run.                                                                                                                                                                                       
                                                                                                                                                                                                               
  Request:                                                                                                                                                                                                     
  {                                                                                                                                                                                                            
    "name": "Test Run 2024-01-17 #1",                                                                                                                                                                          
    "parent_id": "uuid",  // folder ID (required)                                                                                                                                                              
    "test_cases": []      // optional initial test cases                                                                                                                                                       
  }                                                                                                                                                                                                            
                                                                                                                                                                                                               
  Response:                                                                                                                                                                                                    
  {                                                                                                                                                                                                            
    "id": "uuid",                                                                                                                                                                                              
    "name": "Test Run 2024-01-17 #1",                                                                                                                                                                          
    "type": "testrun",                                                                                                                                                                                         
    "parent_id": "uuid",                                                                                                                                                                                       
    "test_cases": [],                                                                                                                                                                                          
    "created_at": "datetime"                                                                                                                                                                                   
  }                                                                                                                                                                                                            
                                                                                                                                                                                                               
  ---                                                                                                                                                                                                          
  4. PATCH /test-run-tree/items/{item_id}                                                                                                                                                                      
                                                                                                                                                                                                               
  Update an item (rename, move, toggle expanded).                                                                                                                                                              
                                                                                                                                                                                                               
  Request:                                                                                                                                                                                                     
  {                                                                                                                                                                                                            
    "name": "Renamed Item",        // optional                                                                                                                                                                 
    "parent_id": "new-parent-id",  // optional - for moving                                                                                                                                                    
    "expanded": true               // optional - for folders                                                                                                                                                   
  }                                                                                                                                                                                                            
                                                                                                                                                                                                               
  Response:                                                                                                                                                                                                    
  {                                                                                                                                                                                                            
    "id": "uuid",                                                                                                                                                                                              
    "name": "Renamed Item",                                                                                                                                                                                    
    "type": "folder",                                                                                                                                                                                          
    "parent_id": "new-parent-id",                                                                                                                                                                              
    "expanded": true,                                                                                                                                                                                          
    "updated_at": "datetime"                                                                                                                                                                                   
  }                                                                                                                                                                                                            
                                                                                                                                                                                                               
  ---                                                                                                                                                                                                          
  5. DELETE /test-run-tree/items/{item_id}                                                                                                                                                                     
                                                                                                                                                                                                               
  Delete a folder or test run (cascading delete for folders).                                                                                                                                                  
                                                                                                                                                                                                               
  Response:                                                                                                                                                                                                    
  {                                                                                                                                                                                                            
    "success": true,                                                                                                                                                                                           
    "deleted_count": 3  // includes children if folder                                                                                                                                                         
  }                                                                                                                                                                                                            
                                                                                                                                                                                                               
  ---                                                                                                                                                                                                          
  6. POST /test-run-tree/items/{item_id}/copy                                                                                                                                                                  
                                                                                                                                                                                                               
  Copy an item (deep copy for folders).                                                                                                                                                                        
                                                                                                                                                                                                               
  Request:                                                                                                                                                                                                     
  {                                                                                                                                                                                                            
    "target_parent_id": "uuid"                                                                                                                                                                                 
  }                                                                                                                                                                                                            
                                                                                                                                                                                                               
  Response:                                                                                                                                                                                                    
  {                                                                                                                                                                                                            
    "id": "new-uuid",                                                                                                                                                                                          
    "name": "Copy of Original",                                                                                                                                                                                
    "type": "folder",                                                                                                                                                                                          
    "parent_id": "target-parent-id"                                                                                                                                                                            
  }                                                                                                                                                                                                            
                                                                                                                                                                                                               
  ---                                                                                                                                                                                                          
  7. PATCH /test-run-tree/testruns/{testrun_id}/test-cases                                                                                                                                                     
                                                                                                                                                                                                               
  Update test cases in a test run.                                                                                                                                                                             
                                                                                                                                                                                                               
  Request:                                                                                                                                                                                                     
  {                                                                                                                                                                                                            
    "test_cases": ["tc-uuid-1", "tc-uuid-2", "tc-uuid-3"]                                                                                                                                                      
  }                                                                                                                                                                                                            
                                                                                                                                                                                                               
  Response:                                                                                                                                                                                                    
  {                                                                                                                                                                                                            
    "id": "uuid",                                                                                                                                                                                              
    "test_cases": ["tc-uuid-1", "tc-uuid-2", "tc-uuid-3"],                                                                                                                                                     
    "updated_at": "datetime"                                                                                                                                                                                   
  }                                                                                                                                                                                                            
                                                                                                                                                                                                               
  ---                                                                                                                                                                                                          
  Summary Table                                                                                                                                                                                                
  ┌────────┬─────────────────────────────────────────┬───────────────────┐                                                                                                                                     
  │ Method │                Endpoint                 │    Description    │                                                                                                                                     
  ├────────┼─────────────────────────────────────────┼───────────────────┤                                                                                                                                     
  │ GET    │ /test-run-tree                          │ Get full tree     │                                                                                                                                     
  ├────────┼─────────────────────────────────────────┼───────────────────┤                                                                                                                                     
  │ POST   │ /test-run-tree/folders                  │ Create folder     │                                                                                                                                     
  ├────────┼─────────────────────────────────────────┼───────────────────┤                                                                                                                                     
  │ POST   │ /test-run-tree/testruns                 │ Create test run   │                                                                                                                                     
  ├────────┼─────────────────────────────────────────┼───────────────────┤                                                                                                                                     
  │ PATCH  │ /test-run-tree/items/{id}               │ Update item       │                                                                                                                                     
  ├────────┼─────────────────────────────────────────┼───────────────────┤                                                                                                                                     
  │ DELETE │ /test-run-tree/items/{id}               │ Delete item       │                                                                                                                                     
  ├────────┼─────────────────────────────────────────┼───────────────────┤                                                                                                                                     
  │ POST   │ /test-run-tree/items/{id}/copy          │ Copy item         │                                                                                                                                     
  ├────────┼─────────────────────────────────────────┼───────────────────┤                                                                                                                                     
  │ PATCH  │ /test-run-tree/testruns/{id}/test-cases │ Update test cases │                                                                                                                                     
  └────────┴─────────────────────────────────────────┴───────────────────┘                                                                                                                                     
  ---                                                                                                                                                                                                          
  Let me know when these APIs are ready, and I'll implement the client-side integration in the testrun_panel.py and create a new service file for these API calls.
